"""add_notifications_and_preferences

Revision ID: 02716c2e4901
Revises: c28c51a6bb22
Create Date: 2026-04-16 02:11:57.481343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '02716c2e4901'
down_revision: Union[str, Sequence[str], None] = 'c28c51a6bb22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preferences',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('user_id', sa.Uuid(), nullable=False),
                    sa.Column('event_created', sa.Boolean(), nullable=False),
                    sa.Column('event_updated', sa.Boolean(), nullable=False),
                    sa.Column('event_cancelled', sa.Boolean(), nullable=False),
                    sa.Column('event_liked', sa.Boolean(), nullable=False),
                    sa.Column('event_commented', sa.Boolean(), nullable=False),
                    sa.Column('user_joined', sa.Boolean(), nullable=False),
                    sa.Column('system_announcements',
                              sa.Boolean(), nullable=False),
                    sa.Column('profile_updates', sa.Boolean(), nullable=False),
                    sa.Column('email_notifications',
                              sa.Boolean(), nullable=False),
                    sa.Column('push_notifications',
                              sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('notifications',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('user_id', sa.Uuid(), nullable=False),
                    sa.Column(
                        'type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('related_id', sa.Uuid(), nullable=True),
                    sa.Column('is_read', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('notification_preferences')
    # ### end Alembic commands ###
