"""add email field to users

Revision ID: 0778735add87
Revises: 02716c2e4901
Create Date: 2026-04-19 11:01:34.602544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0778735add87'
down_revision: Union[str, Sequence[str], None] = '02716c2e4901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column(
        'email', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    op.alter_column('notifications', 'type',
                    existing_type=sa.Enum('EVENT_CREATED', 'EVENT_UPDATED', 'EVENT_CANCELLED', 'EVENT_LIKED', 'EVENT_COMMENTED',
                                          'USER_JOINED', 'SYSTEM_ANNOUNCEMENT', 'PROFILE_UPDATED', name='notificationtype'),
                    type_=sa.VARCHAR(),
                    existing_nullable=False)
    # ### end Alembic commands ###
