"""update models

Revision ID: 40d73391d6d9
Revises: 412ae3209c8a
Create Date: 2026-02-21 23:38:23.753973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '40d73391d6d9'
down_revision: Union[str, Sequence[str], None] = '412ae3209c8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column(
                        'name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('districts',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column(
                        'name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('region_id', sa.Uuid(), nullable=False),
                    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('churches',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column(
                        'name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('district_id', sa.Uuid(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['district_id'], ['districts.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('users', sa.Column(
        'local_church_id', sa.Uuid(), nullable=False))
    op.add_column('users', sa.Column('district_id', sa.Uuid(), nullable=True))
    op.add_column('users', sa.Column('region_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'users', 'districts', ['district_id'], ['id'])
    op.create_foreign_key(None, 'users', 'churches', [
                          'local_church_id'], ['id'])
    op.create_foreign_key(None, 'users', 'regions', ['region_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'region_id')
    op.drop_column('users', 'district_id')
    op.drop_column('users', 'local_church_id')
    op.drop_table('churches')
    op.drop_table('districts')
    op.drop_table('regions')
    # ### end Alembic commands ###
