"""recreate table users

Revision ID: 412ae3209c8a
Revises: ff28c3c916d0
Create Date: 2026-02-16 19:09:15.674631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '412ae3209c8a'
down_revision: Union[str, Sequence[str], None] = 'ff28c3c916d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(
                        length=12), nullable=False),
                    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(
                        length=50), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('is_superuser', sa.Boolean(), nullable=True),
                    sa.Column('is_staff', sa.Boolean(), nullable=True),
                    sa.Column('password_hash', sa.VARCHAR(), nullable=False),
                    sa.Column('last_login', sa.DateTime(), nullable=True),
                    sa.Column('reset_password', sa.Boolean(), nullable=True),
                    sa.Column('password_status',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('login_attempts', sa.Integer(), nullable=True),
                    sa.Column('mobile_login_attempts',
                              sa.Integer(), nullable=True),
                    sa.Column(
                        'token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('reset_token', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=True),
                    sa.Column(
                        'role', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(),
                              nullable=False),
                    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=True),
                    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=True),
                    sa.Column('phone_no', sqlmodel.sql.sqltypes.AutoString(
                        length=10), nullable=False),
                    sa.Column('avatar_image',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('linked', sa.Boolean(), nullable=True),
                    sa.Column('updated_at', postgresql.TIMESTAMP(),
                              nullable=True),
                    sa.Column('mobile_login', sa.Boolean(), nullable=True),
                    sa.Column('last_login_mobile',
                              sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('phone_no')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
