"""Create events table

Revision ID: 4f638bd1b080
Revises: baedb3f4134c
Create Date: 2026-04-12 15:47:02.047984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '4f638bd1b080'
down_revision: Union[str, Sequence[str], None] = 'baedb3f4134c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column(
                        'event_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=True),
                    sa.Column('date_from', sa.DateTime(), nullable=False),
                    sa.Column('date_to', sa.DateTime(), nullable=False),
                    sa.Column(
                        'status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('venue_church_id', sa.Uuid(), nullable=True),
                    sa.Column('venue_district_id', sa.Uuid(), nullable=True),
                    sa.Column('venue_region_id', sa.Uuid(), nullable=True),
                    sa.Column('approved', sa.Boolean(), nullable=True),
                    sa.Column('created_by', sa.Uuid(), nullable=False),
                    sa.Column('approved_by', sa.Uuid(), nullable=True),
                    sa.Column('updated_at', postgresql.TIMESTAMP(),
                              nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(),
                              nullable=False),
                    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
                    sa.ForeignKeyConstraint(
                        ['venue_church_id'], ['churches.id'], ),
                    sa.ForeignKeyConstraint(
                        ['venue_district_id'], ['districts.id'], ),
                    sa.ForeignKeyConstraint(
                        ['venue_region_id'], ['regions.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###
