"""added budget models updated

Revision ID: 5201b61a0ed5
Revises: 9eb189658b18
Create Date: 2026-04-24 18:41:54.109636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5201b61a0ed5'
down_revision: Union[str, Sequence[str], None] = '9eb189658b18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yearly_budgets',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('year', sa.Integer(), nullable=False),
                    sa.Column('total_budget', sa.Numeric(
                        precision=15, scale=2), nullable=False),
                    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_yearly_budgets_year'),
                    'yearly_budgets', ['year'], unique=False)
    op.create_table('dcc_budgets',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('yearly_budget_id', sa.Uuid(), nullable=False),
                    sa.Column('dcc_id', sa.Uuid(), nullable=False),
                    sa.Column('allocated_amount', sa.Numeric(
                        precision=15, scale=2), nullable=False),
                    sa.Column(
                        'status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('approval_date', sa.DateTime(), nullable=True),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(['dcc_id'], ['churches.id'], ),
                    sa.ForeignKeyConstraint(['yearly_budget_id'], [
                                            'yearly_budgets.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_dcc_budgets_dcc_id'),
                    'dcc_budgets', ['dcc_id'], unique=False)
    op.create_index(op.f('ix_dcc_budgets_yearly_budget_id'),
                    'dcc_budgets', ['yearly_budget_id'], unique=False)
    op.create_table('budget_reports',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column(
                        'report_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('report_year', sa.Integer(), nullable=False),
                    sa.Column('report_month', sa.Integer(), nullable=True),
                    sa.Column('dcc_id', sa.Uuid(), nullable=True),
                    sa.Column('local_church_id', sa.Uuid(), nullable=True),
                    sa.Column('total_budgeted', sa.Numeric(
                        precision=15, scale=2), nullable=False),
                    sa.Column('total_paid', sa.Numeric(
                        precision=15, scale=2), nullable=False),
                    sa.Column('total_pending', sa.Numeric(
                        precision=15, scale=2), nullable=False),
                    sa.Column('total_overdue', sa.Numeric(
                        precision=15, scale=2), nullable=False),
                    sa.Column('completion_percentage',
                              sa.Float(), nullable=False),
                    sa.Column('generated_by_id', sa.Uuid(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(['dcc_id'], ['churches.id'], ),
                    sa.ForeignKeyConstraint(
                        ['generated_by_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(
                        ['local_church_id'], ['churches.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_budget_reports_report_type'),
                    'budget_reports', ['report_type'], unique=False)
    op.create_table('local_church_budgets',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('dcc_budget_id', sa.Uuid(), nullable=False),
                    sa.Column('local_church_id', sa.Uuid(), nullable=False),
                    sa.Column('allocated_amount', sa.Numeric(
                        precision=15, scale=2), nullable=False),
                    sa.Column(
                        'status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('approval_date', sa.DateTime(), nullable=True),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['dcc_budget_id'], ['dcc_budgets.id'], ),
                    sa.ForeignKeyConstraint(
                        ['local_church_id'], ['churches.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_local_church_budgets_dcc_budget_id'),
                    'local_church_budgets', ['dcc_budget_id'], unique=False)
    op.create_index(op.f('ix_local_church_budgets_local_church_id'),
                    'local_church_budgets', ['local_church_id'], unique=False)
    op.create_table('budget_payments',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('local_church_budget_id',
                              sa.Uuid(), nullable=False),
                    sa.Column('payment_month', sa.Integer(), nullable=False),
                    sa.Column('payment_year', sa.Integer(), nullable=False),
                    sa.Column('amount_paid', sa.Numeric(
                        precision=15, scale=2), nullable=False),
                    sa.Column('due_date', sa.DateTime(), nullable=False),
                    sa.Column('payment_date', sa.DateTime(), nullable=True),
                    sa.Column(
                        'status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('payment_method',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('reference_number',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('recorded_by_id', sa.Uuid(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(['local_church_budget_id'], [
                        'local_church_budgets.id'], ),
                    sa.ForeignKeyConstraint(
                        ['recorded_by_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_budget_payments_local_church_budget_id'),
                    'budget_payments', ['local_church_budget_id'], unique=False)
    op.create_index(op.f('ix_budget_payments_recorded_by_id'),
                    'budget_payments', ['recorded_by_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_budget_payments_recorded_by_id'),
                  table_name='budget_payments')
    op.drop_index(op.f('ix_budget_payments_local_church_budget_id'),
                  table_name='budget_payments')
    op.drop_table('budget_payments')
    op.drop_index(op.f('ix_local_church_budgets_local_church_id'),
                  table_name='local_church_budgets')
    op.drop_index(op.f('ix_local_church_budgets_dcc_budget_id'),
                  table_name='local_church_budgets')
    op.drop_table('local_church_budgets')
    op.drop_index(op.f('ix_budget_reports_report_type'),
                  table_name='budget_reports')
    op.drop_table('budget_reports')
    op.drop_index(op.f('ix_dcc_budgets_yearly_budget_id'),
                  table_name='dcc_budgets')
    op.drop_index(op.f('ix_dcc_budgets_dcc_id'), table_name='dcc_budgets')
    op.drop_table('dcc_budgets')
    op.drop_index(op.f('ix_yearly_budgets_year'), table_name='yearly_budgets')
    op.drop_table('yearly_budgets')
    # ### end Alembic commands ###
