"""update user field

Revision ID: 7468f3ad4a52
Revises: 0778735add87
Create Date: 2026-04-19 13:11:29.888619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.notifications.models import NotificationType


# revision identifiers, used by Alembic.
revision: str = '7468f3ad4a52'
down_revision: Union[str, Sequence[str], None] = '0778735add87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('users', 'local_church_id',
                    existing_type=sa.UUID(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'local_church_id',
                    existing_type=sa.UUID(),
                    nullable=False)
    op.alter_column('notifications', 'type',
                    existing_type=sa.Enum('EVENT_CREATED', 'EVENT_UPDATED', 'EVENT_CANCELLED', 'EVENT_LIKED', 'EVENT_COMMENTED',
                                          'USER_JOINED', 'SYSTEM_ANNOUNCEMENT', 'PROFILE_UPDATED', name='notificationtype'),
                    type_=sa.VARCHAR(),
                    existing_nullable=False)
    # ### end Alembic commands ###
