"""add fields to event

Revision ID: 85abd409dedd
Revises: b7d737e23655
Create Date: 2026-04-30 22:26:19.584143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '85abd409dedd'
down_revision: Union[str, Sequence[str], None] = 'b7d737e23655'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_programmer',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('events', sa.Column('event_speaker',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'event_speaker')
    op.drop_column('events', 'event_programmer')
    # ### end Alembic commands ###
