"""update notification

Revision ID: b7ab08abed55
Revises: 7468f3ad4a52
Create Date: 2026-04-23 22:34:17.972806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'b7ab08abed55'
down_revision: Union[str, Sequence[str], None] = '7468f3ad4a52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Manually create the ENUM type first
    notification_type = postgresql.ENUM(
        'EVENT_CREATED', 'EVENT_UPDATED', 'EVENT_CANCELLED',
        'EVENT_LIKED', 'EVENT_COMMENTED', 'USER_JOINED',
        'SYSTEM_ANNOUNCEMENT', 'PROFILE_UPDATED',
        name='notificationtype'
    )

    notification_type.create(op.get_bind(), checkfirst=True)
    op.alter_column('notifications', 'type',
                    existing_type=sa.VARCHAR(),
                    type_=sa.Enum('EVENT_CREATED', 'EVENT_UPDATED', 'EVENT_CANCELLED', 'EVENT_LIKED', 'EVENT_COMMENTED',
                                  'USER_JOINED', 'SYSTEM_ANNOUNCEMENT', 'PROFILE_UPDATED', name='notificationtype'),
                    existing_nullable=False, postgresql_using='type::notificationtype')
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('notifications', 'type',
                    existing_type=sa.Enum('EVENT_CREATED', 'EVENT_UPDATED', 'EVENT_CANCELLED', 'EVENT_LIKED', 'EVENT_COMMENTED',
                                          'USER_JOINED', 'SYSTEM_ANNOUNCEMENT', 'PROFILE_UPDATED', name='notificationtype'),
                    type_=sa.VARCHAR(),
                    existing_nullable=False)
    # ### end Alembic commands ###
