"""update user model

Revision ID: baedb3f4134c
Revises: 8f5107c71a6f
Create Date: 2026-02-22 23:07:29.149591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'baedb3f4134c'
down_revision: Union[str, Sequence[str], None] = '8f5107c71a6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_regions_id'), 'regions', ['id'], unique=False)
    op.add_column('users', sa.Column(
        'title', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=False))
    op.add_column('users', sa.Column(
        'rcc_role', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column(
        'dcc_role', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column(
        'lcc_role', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lcc_role')
    op.drop_column('users', 'dcc_role')
    op.drop_column('users', 'rcc_role')
    op.drop_column('users', 'title')
    op.drop_index(op.f('ix_regions_id'), table_name='regions')
    # ### end Alembic commands ###
