"""added fields to event

Revision ID: bd29428f92fd
Revises: 365089a3fdce
Create Date: 2026-04-12 17:01:52.161083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bd29428f92fd'
down_revision: Union[str, Sequence[str], None] = '365089a3fdce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('actual_venue',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('events', sa.Column('target_group',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'target_group')
    op.drop_column('events', 'actual_venue')
    # ### end Alembic commands ###
